name: CD

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build and test base
      uses: gradle/gradle-build-action@v2.10.0
      with:
        arguments: check
        build-root-directory: base
    - name: Build and test aws
      uses: gradle/gradle-build-action@v2.10.0
      with:
        arguments: check
        build-root-directory: aws/library
    - name: AWS integration tests
      run: kotlin run.main.kts
      working-directory: aws/integration-test/example
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-central-1
        AWS_DEFAULT_REGION: eu-central-1
    - name: Deploy base
      uses: gradle/gradle-build-action@v2.10.0
      with:
        arguments: publishAllPublicationsToMavenCentral
        build-root-directory: base
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
    - name: Deploy AWS
      uses: gradle/gradle-build-action@v2.10.0
      with:
        arguments: publishAllPublicationsToMavenCentral
        build-root-directory: aws/library    
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
