name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java_version: [11, 17, 18, 19, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: windows-latest
            java_version: 11
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'temurin'
    - name: configure Pagefile
      uses: al-cheb/configure-pagefile-action@v1.2
      if: matrix.os == 'windows-latest'
      with:
        minimum-size: 6GB
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.9.0
      with:
        arguments: |
          check
          --scan
          --no-daemon
    - name: Upload coverage reports to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.java_version == '11'
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
